/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkersRouteImport } from './routes/_authenticated/workers'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedQueuesRouteImport } from './routes/_authenticated/queues'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConcertsRouteImport } from './routes/_authenticated/concerts'
import { Route as AuthenticatedQueuesQueueNameRouteImport } from './routes/_authenticated/queues/$queueName'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkersRoute = AuthenticatedWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQueuesRoute = AuthenticatedQueuesRouteImport.update({
  id: '/queues',
  path: '/queues',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConcertsRoute = AuthenticatedConcertsRouteImport.update({
  id: '/concerts',
  path: '/concerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQueuesQueueNameRoute =
  AuthenticatedQueuesQueueNameRouteImport.update({
    id: '/$queueName',
    path: '/$queueName',
    getParentRoute: () => AuthenticatedQueuesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/concerts': typeof AuthenticatedConcertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/queues': typeof AuthenticatedQueuesRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/queues/$queueName': typeof AuthenticatedQueuesQueueNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/concerts': typeof AuthenticatedConcertsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/queues': typeof AuthenticatedQueuesRouteWithChildren
  '/users': typeof AuthenticatedUsersRoute
  '/workers': typeof AuthenticatedWorkersRoute
  '/queues/$queueName': typeof AuthenticatedQueuesQueueNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/concerts': typeof AuthenticatedConcertsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/queues': typeof AuthenticatedQueuesRouteWithChildren
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/workers': typeof AuthenticatedWorkersRoute
  '/_authenticated/queues/$queueName': typeof AuthenticatedQueuesQueueNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/concerts'
    | '/dashboard'
    | '/queues'
    | '/users'
    | '/workers'
    | '/queues/$queueName'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/concerts'
    | '/dashboard'
    | '/queues'
    | '/users'
    | '/workers'
    | '/queues/$queueName'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/concerts'
    | '/_authenticated/dashboard'
    | '/_authenticated/queues'
    | '/_authenticated/users'
    | '/_authenticated/workers'
    | '/_authenticated/queues/$queueName'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workers': {
      id: '/_authenticated/workers'
      path: '/workers'
      fullPath: '/workers'
      preLoaderRoute: typeof AuthenticatedWorkersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queues': {
      id: '/_authenticated/queues'
      path: '/queues'
      fullPath: '/queues'
      preLoaderRoute: typeof AuthenticatedQueuesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/concerts': {
      id: '/_authenticated/concerts'
      path: '/concerts'
      fullPath: '/concerts'
      preLoaderRoute: typeof AuthenticatedConcertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queues/$queueName': {
      id: '/_authenticated/queues/$queueName'
      path: '/$queueName'
      fullPath: '/queues/$queueName'
      preLoaderRoute: typeof AuthenticatedQueuesQueueNameRouteImport
      parentRoute: typeof AuthenticatedQueuesRoute
    }
  }
}

interface AuthenticatedQueuesRouteChildren {
  AuthenticatedQueuesQueueNameRoute: typeof AuthenticatedQueuesQueueNameRoute
}

const AuthenticatedQueuesRouteChildren: AuthenticatedQueuesRouteChildren = {
  AuthenticatedQueuesQueueNameRoute: AuthenticatedQueuesQueueNameRoute,
}

const AuthenticatedQueuesRouteWithChildren =
  AuthenticatedQueuesRoute._addFileChildren(AuthenticatedQueuesRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedConcertsRoute: typeof AuthenticatedConcertsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedQueuesRoute: typeof AuthenticatedQueuesRouteWithChildren
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedWorkersRoute: typeof AuthenticatedWorkersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedConcertsRoute: AuthenticatedConcertsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedQueuesRoute: AuthenticatedQueuesRouteWithChildren,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedWorkersRoute: AuthenticatedWorkersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
